name: Code Security Scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  code-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit scan (JSON output)
        run: |
          bandit -r . -f json -o bandit_output.json || true
          cat bandit_output.json

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep scan (JSON output)
        run: |
          semgrep --config auto --json > semgrep_output.json || true
          cat semgrep_output.json

      - name: Archive code scan results
        uses: actions/upload-artifact@v4
        with:
          name: code-scan-results
          path: |
            bandit_output.json
            semgrep_output.json
