name: Code Security Scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r ./app

  semgrep_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Semgrep
        run: |
          curl -sL https://raw.githubusercontent.com/returntocorp/semgrep/master/install.sh | sh

      - name: Run Semgrep Scan
        run: semgrep --config=p/ci
