name: Docker Image Security Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in repo root
        run: ls -l

      - name: Build Docker image
        run: docker build -t cysec-ci-cd-app -f Dockerfile .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.8.0
        with:
          image-ref: cysec-ci-cd-app

      - name: Scan Docker image with Grype
        uses: anchore/grype-action@v0.10.0
        with:
          image: cysec-ci-cd-app
