name: Docker Image Security Scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  docker-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t cysec-ci-cd-app .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy scan (fail on HIGH/CRITICAL)
        run: |
          trivy image --format json --severity HIGH,CRITICAL --exit-code 1 --output trivy_output.json cysec-ci-cd-app

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Grype scan (fail on HIGH/CRITICAL)
        run: |
          grype cysec-ci-cd-app -o json > grype_output.json
          jq '.matches[] | select(.vulnerability.severity=="High" or .vulnerability.severity=="Critical")' grype_output.json | grep . || exit 0
          echo "High/Critical vulnerabilities found"
          exit 1

      - name: Archive scan results
        uses: actions/upload-artifact@v4
        with:
          name: docker-scan-results
          path: |
            trivy_output.json
            grype_output.json
