name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd sample_app
        pip install -r requirements.txt

    - name: Run basic test
      run: |
        cd sample_app
        python app.py

    - name: Run Bandit scan
      run: |
        pip install bandit
        bandit -r sample_app -f json -o bandit_results.json || true

    - name: Run Semgrep scan
      run: |
        curl -sL https://semgrep.dev/install.sh | bash
        ./semgrep/semgrep --config=p/ci sample_app --json > semgrep_results.json || true

    - name: Upload scan results
      uses: actions/upload-artifact@latest
      with:
        name: scan-results
        path: |
          bandit_results.json
          semgrep_results.json
