name: Security CI/CD Pipeline

on: [push, pull_request]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Bandit & Semgrep
        run: |
          pip install bandit semgrep

      - name: Run Bandit Code Scan
        run: bandit -r . -f json -o bandit_report.json

      - name: Run Semgrep Code Scan
        run: semgrep --config=auto --json > semgrep_report.json

      - name: Run Trivy Docker Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: your-image:latest
          format: json
          output: trivy_report.json

      - name: Run Grype Docker Scan
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b $HOME/.local/bin
          ~/.local/bin/grype your-image:latest -o json > grype_report.json

      - name: Upload Scan Results
        uses: actions/upload-artifact@v3.0.2
        with:
          name: security-reports
          path: |
            bandit_report.json
            semgrep_report.json
            trivy_report.json
            grype_report.json
