name: Docker Image Security Scan

on:
  push:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cysec-ci-cd-app .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy scan (fail on high/critical, save JSON)
        run: trivy image --exit-code 1 --format json --output trivy-report.json cysec-ci-cd-app

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Grype scan (fail on high/critical, save JSON)
        run: grype -o json cysec-ci-cd-app > grype-report.json

      - name: Upload scan reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-reports
          path: |
            trivy-report.json
            grype-report.json
