name: Security CI

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install scanners
      run: |
        pip install bandit semgrep
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh
     - name: Create output directories
       run: |
        mkdir -p scans/code
        mkdir -p scans/image

    - name: Run Bandit
      run: bandit -r . -f json -o scans/code/bandit.json

    - name: Run Semgrep
      run: semgrep scan --config=auto --json --output=scans/code/semgrep.json

    - name: Build Docker Image
      run: docker build -t insecure-app .

    - name: Trivy Scan
      run: ./trivy image -f json -o scans/image/trivy.json insecure-app

    - name: Grype Scan
      run: ./grype insecure-app -o json > scans/image/grype.json

#    - name: Upload scan results
 #     uses: actions/upload-artifact@v4.
  #    with:
   #     name: scan-results
    #    path: scans/
